#  Notes on Operator Inference on Shallow Water Equation


## Introduction
In this notes we discuss the Goal-Oriented Arbitrary Manifold Operator Inference.

Consider a time evolution system toy problem $\frac{\partial x}{\partial t} = F(x;p)$ with state variable $x \in R^n$ and parameter $p \in R^m$, say shallow water equation and wave equation. And also we consider an quantity of interest(QoI) $q = q(x;p) \in R^d$.

We consider the following model reduction approach: Suppose $\hat x = \hat x(t;p) \in R^r$ is a reduced state variable which encode the low dimensional dynamics of $x$. $\hat x$ must follow some dynamics, which we propose two possibilities: 
- Linear Model: $\frac{\partial \hat x}{\partial t} = B \hat x + D p$, where $B \in R^{r \times r}, D \in R^{r \times m}$
- Quadratic Model: $\frac{\partial \hat x}{\partial t} = B \hat x + C \hat x \otimes \hat x + D p$, where $B \in R^{r \times r}, C \in R^{r \times s}$, where $s = \frac{r(r+1)}{2}, x \otimes x $ is the vector containing all the quadratic terms $x_ix_j$

We assume the quantity of interst $q$ is related to $\hat x$ via some linear operator $A \in R^{d \times r}$. Suppose we have several values of parameter $p_1,p_2,\dots,p_k$, and we get measurements of quantity of interest at moments $t_1 < t_2 < \dots < t_l $, then
 Then we arrive at the following optimization problem:

\begin{align*}
 &\min_{A \in R^{d \times r}, B \in R^{r \times r}, C \in R^{r \times s}, D \in R^{r \times m}}\quad L(A,\hat x(B,C,D)) =  \frac{1}{2}\sum_{i = 1}^k \sum_{j = 1}^l \|A\hat x_i(t_j) - q_i(t_j)\|_2^2 + \text{Regularization terms} \\ &\text{ where } \hat x_i(B,C,D) \text{ solves }\frac{\partial \hat x_i}{\partial t} = B \hat x_i + C \hat x_i \otimes \hat x_i + D p_i, \hat x_i(0) = 0
 \tag{P}
 \end{align*}




## Solving the Optimization Problem

First we can observe that there is a equivalent class of solution. Specifically, if $(A,B,C,D)$ is one optimal solution to the problem and $Q \in R^{r \times r}$ is an invertible matrix, then $(\tilde A, \tilde B, \tilde C, \tilde D)$ is also optimal, where $\tilde A = AQ^{-1}, \tilde B = QBQ^{-1} , \tilde D = QD, \tilde C \hat x\otimes \hat x = Q C ( Q^{-1}\hat x) \otimes Q^{-1} (\hat x) $

Since we allow a similar transform of the matrix $B$, we can put the constrain that $B$ is upper-triangular. Then we discuss how to compute the derivative of $L$ regarding to $A,B,C,D$.

For simplicity, we just consider the case where $k = 1$, i.e. there is only one parameter $p$.

### Derivative Regarding $A$:  

  Let $f(A) = \frac{1}{2}\|Ax - q\|_2^2$. Consider the perturbation $A \to A + c \Delta A$, then we have:
  \begin{align*}
   \delta f = \lim_{c \to 0} \frac{f(A + c\Delta A) - f(A)}{c} 
   &= \lim_{c \to 0}\frac{1}{2c}(Ax + c\Delta A - q)^T(Ax + c\Delta A - q) - (Ax -q)^T(Ax - q) \\
   &= \left< \Delta A, (Ax - q)x^T \right>_{R^{r \times r}}
  \end{align*}
  
  Where$ \left<A,B \right>_{R^{r \times r}}$ is the inner product on matrix space $R^{r \times r}$ defined by $\left<A, B \right>_{R^{r\times r}} := \operatorname{tr}(A^TB)$ 
  
  Thus $\frac{\delta f}{ \delta A} = (Ax - b)x^T$, $\frac{\delta L}{\delta A} = \sum_{j=1}^l (Ax(t_j) - q_j)x^T(t_j)$
  





### Derivative Regarding $B$:

  Consider $x = x(t;B)$ as a function of $B$, let $f(B) = \frac{1}{2} \|Ax(T;B) - q\|_2^2$, where $T$ is a fixed moment. Then we know 
  \begin{equation*}
  \frac{\delta f}{\delta B} = \left<A^Tr, \frac{\delta x(T;B)}{\delta B} \right>_{R^d} , \text{ where } r = Ax(T;B) - q
  \end{equation*}
  
  $\frac{\delta x(T;B)}{\delta B}$ can be calculated through the following way: consider perturbation $\tilde B = B + c\Delta B$,where $c \ll 1$, let $\tilde x = x(T;B + c\Delta B)$, then we have
  \begin{align*}
  \frac{\partial \tilde x}{\partial t} &= (B + c\Delta B) \tilde x + C \tilde x\otimes \tilde x + Dp, \tilde x(0) = 0
  \end{align*}
    
  Compute the derivative of $\tilde x$ regarding to $c$ at $c = 0$, we have
  \begin{align*}
  \frac{\partial}{\partial t} \frac{\partial \tilde x}{\partial c} &=  B \frac{\partial \tilde x}{ \partial c} + \Delta B x + C \frac{\partial \tilde x}{\partial c} \otimes x + C x \otimes \frac{\partial \tilde x}{\partial c} , \frac{\partial \tilde x}{\partial c}(0;B) = 0  \end{align*}
  
  Let $\mathcal{G}$ be a linear operator $\mathcal{G}u = Bu + C x \otimes u + C u \otimes x$ on $R^r$, then we have
  \begin{equation*}
  \frac{\partial}{\partial t} \frac{\partial \tilde x}{\partial c} = \mathcal{G}\frac{\partial \tilde x}{\partial c} + \Delta B x , \frac{\partial x}{\partial c}(0;B) = 0
  \end{equation*}
  
  By Duhamel principle, $\frac{\partial \tilde x}{\partial c}(T)$ can be expressed by
  \begin{equation*}
  \frac{\partial \tilde x}{\partial c} = \int_{0}^T \exp(\mathcal{G}(t-s)) \Delta B \tilde x(s) ds
  \end{equation*}
  
  Then for given disturb direction $\Delta B$, we have
  \begin{align*}
   \frac{\partial f}{\partial c} &= \left< A^T r, \frac{\partial \tilde x}{\partial c}(T) \right>_{R^d}  \\
   &= \left< A^T r, \int_{0}^T \exp(\mathcal{G}(t-s)) \Delta B x(s) ds  \right>_{R^d}  \\
   & = \int_{0}^T \left< A^Tr, \exp(\mathcal{G}(t-s)) \Delta B x(s) \right>_{R^d} ds \\
   & = \int_{0}^T \left<\Delta B x(s), [\exp(\mathcal{G}(t-s))]^* A^T r \right>_{R^d} ds \\
   & = \left<\Delta B, \int_{0}^T [\exp(\mathcal{G}(t-s))]^* A^T r x(s)^T ds  \right>_{R^{r \times r}}
   \end{align*}
  
  Note that $[\exp(\mathcal{G}(t-s))]^* = \exp(\mathcal{G^*}(t-s))$. Thus $\frac{\delta f}{\delta B} = \int_0^T \tilde r(s)x(s)^T ds$, where $\tilde r(s)$ solves the equation
\begin{equation*}
    \frac{\partial \tilde r}{\partial t} = -\mathcal{G}^* \tilde r,    \tilde r (T) = A^T r 
\end{equation*}

  
 
  

For whole $L(x) = \frac{1}{2}\sum_{j=1}^l \|Ax(t_j) - q_j\|_2^2$, we have
\begin{equation*}
    \frac{\delta L}{\delta B} = \sum_{j=1}^l \int_0^{t_j} \tilde r_j(s)x(s)^T ds, \text{ where } \tilde r_j \text{ solves the equation } \frac{\partial \tilde r_j}{\partial t} = -G^*\tilde r_j, \tilde r(t_j) = A^T(Ax(t_j) - q_j)
\end{equation*}

### Derivative Regarding C

Using same approach as computing derivative regarding $B$. First consider $f(x) = \frac{1}{2}\|Ax(t;C) - b\|_2^2$. 

Consider perturbation $\tilde C = C + c\Delta C$. The resulting $\tilde x$ satisfies the following equation:
\begin{equation*}
      \frac{\partial \tilde x}{\partial t} = B \tilde x + (C + c\Delta C) \tilde x\otimes \tilde x + Dp, \tilde x(0) = 0
\end{equation*}

Take derivative on $c$ at $c = 0$, and recall $\mathcal{G}u = Bu + C x \otimes u + C u \otimes x$ on $R^r$, we have 
\begin{equation*}
      \frac{\partial}{\partial t} \frac{\partial \tilde x}{\partial c} = \mathcal{G} \frac{\partial x}{\partial c} +  \Delta C  x \otimes x, \frac{\partial \tilde x}{\partial c}(0) = 0
\end{equation*}

Thus we have 
\begin{equation*}
    \frac{\partial f}{\partial c} = \left< \Delta C, \int_0^T [\exp(\mathcal{G}(t-s))]^* A^T r [x(s) \otimes x(s) ]^T ds   \right>_{R^{r \times s}} 
\end{equation*}










For whole $L(x) = \frac{1}{2}\sum_{j=1}^l \|Ax(t_j) - q_j\|_2^2$, we have
\begin{equation*}
    \frac{\delta L}{\delta C} = \sum_{j=1}^l \int_0^{t_j} \tilde r_j(s) [x(s) \otimes x(s)]^T ds, \text{ where } \tilde r_j \text{ solves the equation } \frac{\partial \tilde r_j}{\partial t} = -G^*\tilde r_j, \tilde r(t_j) = A^T(Ax(t_j) - q_j)
\end{equation*}

### Derivative Regarding D



Consider $f(x) = \frac{1}{2}\|Ax(t;D) - b\|_2^2$ and perturbation $\tilde D = D + c\Delta D$. The resulting $\tilde x$ satisfies the following equation:
\begin{equation*}
      \frac{\partial \tilde x}{\partial t} = B \tilde x + C \tilde x\otimes \tilde x + (D + c\Delta D)p, \tilde x(0) = 0
\end{equation*}

Take derivative on $c$ at $c = 0$, and recall $\mathcal{G}u = Bu + C x \otimes u + C u \otimes x$ on $R^r$, we have 
\begin{equation*}
      \frac{\partial}{\partial t} \frac{\partial \tilde x}{\partial c} = \mathcal{G} \frac{\partial x}{\partial c} +  \Delta D  p, \frac{\partial \tilde x}{\partial c}(0) = 0
\end{equation*}

Thus we have 
\begin{equation*}
    \frac{\partial f}{\partial c} = \left< \Delta D, \int_0^T [\exp(\mathcal{G}(t-s))]^* A^Tr p(s)^T ds   \right>_{R^{r \times m}} 
\end{equation*}

For whole $L(x) = \frac{1}{2}\sum_{j=1}^l \|Ax(t_j) - q_j\|_2^2$, we have
\begin{equation*}
    \frac{\delta L}{\delta D} = \sum_{j=1}^l \int_0^{t_j} \tilde r_j(s) p(s)^T ds, \text{ where } \tilde r_j \text{ solves the equation } \frac{\partial \tilde r_j}{\partial t} = -G^*\tilde r_j, \tilde r(t_j) = A^T(Ax(t_j) - q_j)
\end{equation*}


## Computing the Adjoint Equation

Remind that $\mathcal{G}:R^r \to R^r, \mathcal{G}u = Bu + C (u \otimes x + x \otimes u)$, where $B \in R^{r \times r}, C \in R^{r \times s}$

We write $x \otimes y = I(xy^T)$, where $I: R^{r\times r} \to R^s$ is a restriction operator of the upper triangular part, i.e.
\begin{equation*}
    I: R^{r\times r} \to R^s, I(A)
      = (a_{11},a_{12}, \dots, a_{1r}, a_{22},a_{23},\dots,a_{2r},\dots,a_{rr})^T, \text{ where }A = \begin{pmatrix} a_{11} & a_{12} & \dots &a_{1r} \\ 
                                                a_{21} & a_{22} & \dots &a_{2r} \\ 
                                                \dots & \dots & \dots & \dots \\ 
                                                a_{r1} & a_{r2} & \dots & a_{rr} \end{pmatrix}
\end{equation*}

Then the adjoint operator of $I$ is rearranging a vector in $R^s$ to the upper triangular of a matrix:
\begin{equation*}
I ((a_{11},a_{12}, \dots, a_{1r}, a_{22},a_{23},\dots,a_{2r},\dots,a_{rr})^T ) = \begin{pmatrix} a_{11} & a_{12} & \dots &a_{1r} \\ 
                                                0 & a_{22} & \dots &a_{2r} \\ 
                                                \dots & \dots & \dots & \dots \\ 
                                                0 & 0 & \dots & a_{rr} \end{pmatrix}
\end{equation*}

Let $C = (c_1,c_2,\dots,c_r) \in R^{s \times r}$, where $c_i \in R^s$. To compute $\mathcal{G}^*$, we have 
\begin{align*}
    \left< \mathcal{G}u,v \right>_{R^r} &= \left< Bu + C u \otimes x + C x \otimes u, v \right>_{R^r}  \\
    &=  \left<u ,B^* v\right>_{R^r} + \left< C \circ I(xu^T + ux^T), v   \right>_{R^r} \\ 
    &=  \left<u ,B^* v\right>_{R^r} + \left< xu^T + ux^T, I^*(C^* v) \right>_{R^{r \times r}}\\
    &=  \left<u ,B^* v\right>_{R^r} + \operatorname{tr}( (xu^T + ux^T)I^*(C^* v)   ) \\
    &=  \left<u ,B^* v\right>_{R^r} + \left< u, [I^*(C^* v) + (I^*(C^* v))^T ]x  \right>_{R^r} \\
    &=  \left<u ,B^* v + [I^*(C^* v) + (I^*(C^* v))^T ]x \right>_{R^r}
\end{align*}

Thus we have that $G^*v = B^* v + [I^*(C^* v) + (I^*(C^* v))^T ]x$






## Initialization 

In this part we discuss how to choose a proper initialization for the operator inference setting.

This initialization approach is motivated from the traditional POD and operator inference framework. To use this approach, We assume we have access to the high-fidelity model $x(\cdot)$. 

Recall the reduced-order dynamics we are constructing is 
\begin{equation*}
    \frac{\partial x_r}{\partial t} = Bx_r + C x_r \otimes x_r + D p
\end{equation*}

And we are proposing $q = A x_r$ for computing the quantity of interest, where $A,B,C,D$ are operator to be determined.

The initialization motivated from POD is constructed as follows:

1) Compute a reduced order basis $V \in R^{n \times r}$ from the snapshot of the high-fidelity model $x(\cdot)$, compute $\hat x_r(t_i) = V^T x(t_i), i = 1,2,\dots,N$

2) The initialization of $A$ is given by the optimization problem:
\begin{equation*}
    \min_{A \in R^{r \times d}}\sum_{i=1}^N \| Ax_r(t_i) - q(t_i) \|_2^2 + \lambda_A \|A\|_F^2
\end{equation*}

3) The initialization of $B,C,D$ is computed by the optimization problem:
\begin{equation*}
    \min_{B,C,D \in R^{r \times d}}\sum_{i=1}^N \| \dot{x_r}(t_i) - (B {x_r} + C x_r \otimes x_r + D p_i)  \|_2^2 + \lambda_B \|B\|_F^2 + \lambda_C \|C\|_F^2 + \lambda_D \|D\|_F^2
\end{equation*}

While the optimization problem can be solved by least square, we need the time derivative to formulate it. To obtain the time derivative of $x_r$, we have two possible ways:
- Use numerical derivative. Note that a simple forward or backward discretization method would bring in large numerical error when the time discretization is not fine enough. This problem is somehow mitigated by using high order numerical derivative in Opinf package authored by Karen's group.

- If we have the original dynamics $\dot x = f(x)$, then the time derivative can be accessed by $\dot x_r(t_i) = V^T f(x(t_i))$. It's reasonable to assume we have access to the original dynamics, if we are considering the shallow water equation.

##  Alternative Optimization Technique


In previous session we discuss the optimization framework where $x_r(\cdot)$ is treated as a function of $A,B,C,D$ , which results in an unconstrained optimization problem w.r.t. $A,B,C,D$. The problem is that there will be certain range of $B,C,D$ so that the quadratic dynamics $\dot x_r = Bx_r + Cx_r \otimes x_r + D p_i$ is stable during time evolution. Unfortunately, the set $\{B,C,D: \text{the reduced dynamic is stable}\}$ can not be specified due to our lack of knowledge about this quadratic system. So we are proposing another kind of optimization technique here, where we treat $x$ and $B,C,D$ separately.























In [1]:
# Validating our computation of the adjoint operator
r = 10;   s = int(r * (r+1) / 2)
x = np.random.rand(r,1);  x = x.reshape([r,1])
#B = np.random.rand(r,r);  
B = np.zeros([r,r])
C = np.random.rand(r,s)
def G(u,x):
    indicelist = np.triu_indices(r)
    tmp = u * x.T + x * u.T
    tmp2 = tmp[indicelist]
    tmp2 = tmp2.reshape([s,1])
    answ = np.dot(B,x) + np.dot(C,tmp2)
    answ = answ.reshape(r,1)
    return answ

def G_adj(v,x):
    indicelist = np.triu_indices(r)
    tmp = np.dot(C.T,v)
    A = np.zeros([r,r])
    A[indicelist] = np.array(list(tmp.T))
    answ = np.dot(A + A.T, x) + np.dot(B.T,v)
    answ = answ.reshape(r,1)
    return answ

for i in range(10):
    u = np.random.rand(r,1);    v = np.random.rand(r,1);
    gu = G(u)
    S1 = float(np.dot(gu.T,v))
    S2 = float(np.dot(u.T,G_adj(v)))
    print(S1,S2)


NameError: name 'np' is not defined

In [ ]:
S1

In [ ]:
indicelist = np.triu_indices(r)
tmp = np.dot(C.T,v)
A = np.zeros([r,r])
B = np.random.rand(r,r)
tmp2 = B[indicelist]
tmp3 = np.array(list(tmp.T))
A[indicelist] = tmp3
len(indicelist[0])

In [ ]:
list(tmp.T)

In [31]:
u = np.arange(r).reshape([r,1])
A = u * x.T


In [35]:
print(u[2],x[5],A[2,5])

[2] [0.71060513] 1.421210259644987


## Optimization Algorithm


### Solving Equations

Thus, to update $A,B,C,D$, we need to solve two equations in each iteration: the forward problem and the adjoint equation.
\begin{align*}
    \text{ Forward Problem: }& \frac{\partial x}{\partial t} = Bx + C x\otimes x + Dp,  x(0) = 0
\\
    \text{ Adjoint Equation: }& \frac{\partial \tilde r_j}{\partial t} = -G^*\tilde r_j, \tilde r(t_j) = A^T(Ax(t_j) - q_j), \text{ where } \mathcal{G}u = Bu + C x \otimes u + C u \otimes x, j = 1,2,\dots,l
\end{align*}

Reverse the time variable in the adjoint equation, adjiont equation is equivalent to the following:
\begin{equation*}
    \frac{\partial \tilde r_j}{\partial t} = G^* \tilde r_j , \tilde r(0) = A^T(Ax(t_j) - q_j) 
\end{equation*}

Remark: 
- The forward problem is quadratic, while the adjoint equation is linear
- Since the operator $\mathcal{G}$ depends on $x$, thus we need to formulate $\mathcal{G}$ in each iteration.
- There is no need to solve the adjoint equation for $l$ times. According to Duhamel Principal, we can sum up all $l$ terms by evolving the system from the largest $t_l$ and add the source term when time gets to $t_j$.


### Initialization of Optimization Problem

Now to discuss the strategy of choosing the initial value.

Consider the following optimization problem: Find $A \in R^{d \times r}, B \in R^{r \times r}, C \in R^{r \times s}, D \in R^{r \times m}$
\begin{equation*}
    \text{minimize }_{A,B,C,D}  \sum_{i=1}^{N_t} | A x_r(t_i) - q_i  \|_2^2, \text{s.t. } \dot x_r = Bx_r + Cx_r \otimes x_r + D p
\end{equation*}

We need some strategy to set up the initial value of $A,B,C,D$. The simplest approach is set $A = 0, B = 0, C = 0, D = 0$. Unfortunately this can not work as this is actually a saddle point of original problem hence contains no information about optimal minimum.

Another approach is to initialize $A,B,C,D$ randomly. This can works in practice, but it has the risk that the initial value of $C$ can make the system becomes unstable. Here we discuss another approach which is motivated via traditional operator inference.

In this approach, we suppose the high fidelity solution is available. Then we need to do the following:
- Use high fidelity model $x(t)$ to generate classical POD snapshot $\hat x_r(t) = Vx(t)$, where $V \in R^{r \times N}$, $N$ is the dimension of high fidelity model.
- Compute $A,B,C,D$ such that 
\begin{align*}
A &= \arg \min \sum_{i=1}^{N_t} \|A \hat x_r(t_i) - q(t_i) \|_2^2  \\
B,C,D &= \arg \min \sum_{i=1}^{N_t} \| \frac{\partial}{\partial t}\hat x_r(t_i) -  B \hat x_r(t_i) - C \hat x_r \otimes \hat x_r (t_i) - D p(t_i) \|^2_2
\end{align*} 


Then we discuss how to compute $A,B,C,D$ using least square.


#### About A

Consider two cases: 

1) 
    If the quantity of interest $q$ is a linear operator of $x$, i.e. $q = Lx, L \in R^{d \times N}$, then we have
\begin{equation}
    \|A\hat x_r - q\|_2^2 = \| AV x - Lx \|_2^2
\end{equation}
    To optimize $\|L - AV\|^2_F$, the solution is given by $A = LV^T$. This use the fact that the POD basis $V$ is orthogonal, i.e. $VV^T = I_r$.
    
2)
    If the quantity of interest $q$ is not a linear operator of $x$, then we need to solve 
    \begin{equation}
            \sum_{i=1}^{N_t} \|A\hat x_r(t_i) - q(t_i) \|_2^2
    \end{equation}
    Let $X = \begin{pmatrix}
        x_r(t_1) & x_r(t_2) & \dots x_r(t_{N_t})
    \end{pmatrix} \in R^{r \times N_t}$, $Q = \begin{pmatrix} q(t_1) & q(t_2) & \dots q(t_{N_t}) \end{pmatrix} \in R^{d \times N_t}$, then we need to solve following:
    \begin{equation}
        A = \arg \min_A \|AX - Q\|_F^2
    \end{equation}
    The normal equation of this optimization problem reads as $(AX - Q)X^T = 0$

###    
#### About B,C,D
For $B \in R^{r \times r},C \in R^{r \times s },D \in R^{r \times m}$, we need to solve the following optimization: 
\begin{equation}
B,C,D = \arg \min \sum_{i=1}^{N_t} \| \frac{\partial}{\partial t}\hat x_r(t_i) -  B \hat x_r(t_i) - C \hat x_r \otimes \hat x_r (t_i) - D p(t_i) \|^2_2
\end{equation}

Let \begin{align}
V &= \begin{pmatrix}
        \frac{\partial}{\partial t}x_r(t_1) & \frac{\partial}{\partial t}x_r(t_2) & \dots & \frac{\partial}{\partial t} x_r(t_{N_t}) 
    \end{pmatrix} \in R^{r \times N_t} \\
X &= \begin{pmatrix}
        x_r(t_1) & x_r(t_2) & \dots x_r(t_{N_t})
    \end{pmatrix} \in R^{r \times N_t} \\
Y &= \begin{pmatrix}
        x_r \otimes x_r (t_1)  & x_r \otimes x_r (t_2) & \dots x_r \otimes x_r (t_{N_t})
    \end{pmatrix} \in R^{s \times N_t} \\
Z &= \begin{pmatrix} p(t_1) & p(t_2) \dots & p(t_{N_t})
    \end{pmatrix} \in R^{m \times N_t} \\
U &= \begin{pmatrix}B & C &D \end{pmatrix} \in R^{r \times (r + s + m)} \\
W &= \begin{pmatrix}{X \\ Y \\ Z}\end{pmatrix} \in R^{(r + s+ m) \times N_t}
    \end{align}
    
Then the optimization problem reads as $U = \arg \min_U \|V - UW\|^2_F$

#### Solver for least square

For $X \in R^{r \times N}, A \in R^{d \times r}, B \in R^{d \times N}$, to solve $A = \arg \min_A \| AX - B \|_F^2$, let $X^T = QR$, where $Q \in R^{N \times N}, R \in R^{N \times r}$, then $X = R^TQ^T$, and we have 
\begin{equation}
\|AX - B\|^2_F = \|X^TA^T - B^T\|_F^2 = \|QRA^T - B^T \|_F^2 = \|RA^T - Q^TB^T\|_F^2
\end{equation}

Thus we have $A^T = R_{[1:r, 1:r]}^{-1} (Q^TB^T)_{[1:r,:]}$, or $A = (BQ)_{[:,1:r]} (R_{[1:r, 1:r]})^{-T}$



### Optimization Step

Assume we get all derivatives $\frac{\partial L}{\partial A},\frac{\partial L}{\partial B},\frac{\partial L}{\partial C},\frac{\partial L}{\partial D}$. Then we need to use appropriate scheme to update $A,B,C,D$.

The optimization is done with the help of scipy.optimize.


## Initialization 

In this part we discuss how to choose a proper initialization for the operator inference setting.

This initialization approach is motivated from the traditional POD and operator inference framework. To use this approach, We assume we have access to the high-fidelity model $x(\cdot)$. 

Recall the reduced-order dynamics we are constructing is 
\begin{equation*}
    \frac{\partial x_r}{\partial t} = Bx_r + C x_r \otimes x_r + D p
\end{equation*}

And we are proposing $q = A x_r$ for computing the quantity of interest, where $A,B,C,D$ are operator to be determined.

The initialization motivated from POD is constructed as follows:

1) Compute a reduced order basis $V \in R^{n \times r}$ from the snapshot of the high-fidelity model $x(\cdot)$, compute $\hat x_r(t_i) = V^T x(t_i), i = 1,2,\dots,N$

2) The initialization of $A$ is given by the optimization problem:
\begin{equation*}
    \min_{A \in R^{r \times d}}\sum_{i=1}^N \| Ax_r(t_i) - q(t_i) \|_2^2 + \lambda_A \|A\|_F^2
\end{equation*}

3) The initialization of $B,C,D$ is computed by the optimization problem:
\begin{equation*}
    \min_{B,C,D \in R^{r \times d}}\sum_{i=1}^N \| \dot{x_r}(t_i) - (B {x_r} + C x_r \otimes x_r + D p_i)  \|_2^2 + \lambda_B \|B\|_F^2 + \lambda_C \|C\|_F^2 + \lambda_D \|D\|_F^2
\end{equation*}

While the optimization problem can be solved by least square, we need the time derivative to formulate it. To obtain the time derivative of $x_r$, we have two possible ways:
- Use numerical derivative. Note that a simple forward or backward discretization method would bring in large numerical error when the time discretization is not fine enough. This problem is somehow mitigated by using high order numerical derivative in Opinf package authored by Karen's group.

- If we have the original dynamics $\dot x = f(x)$, then the time derivative can be accessed by $\dot x_r(t_i) = V^T f(x(t_i))$. It's reasonable to assume we have access to the original dynamics, if we are considering the shallow water equation.

##  Alternative Optimization Technique


In previous session we discuss the optimization framework where $x_r(\cdot)$ is treated as a function of $A,B,C,D$ , which results in an unconstrained optimization problem w.r.t. $A,B,C,D$. The problem is that there will be certain range of $B,C,D$ so that the quadratic dynamics $x_r = Bx_r + Cx_r \otimes x_r + D p_i$ is stable during time evolution. Unfortunately, the set $\{B,C,D: \text{the reduced dynamic is stable}\}$ can not be specified due to our lack of knowledge about this quadratic system. So we are proposing another kind of optimization technique here, where we treat $x$ and $B,C,D$ separately.

For simplicity, we use the notation $f_r(x_r;B,C,D) = Bx_r + Cx_r \otimes x_r + D p_i$, where the subscript shows that $f_r$ acts on the reduced variable $x_r$, which is a reduction of the high fidelity dynamics $f$.

The optimization problem we are proposing here is 
\begin{equation*}
  \min_{x_r(t_i),A,B,C,D}  \sum_{i=1}^N \|Ax_r(t_i) - q_i\|_2^2 + \mu  \sum_{i=1}^{N-1} \| x_r(t_{i+1}) - x_r(t_i) - \int_{t_i}^{t_{i+1}} f_r(x_r(s);B,C,D) ds \|_2^2 + \text{regularization terms}
\end{equation*}

The first term is the misfit of quantity of interest, while the second term is the error of the reduced dynamics in integration form. We use the integration form here to avoid the possible large error due to numerical evaluation of the time derivative. The parameter $\mu$ here will be increased during the optimization procedure, to ensure that the reduced dynamics is satisfied
























Let $\phi(x;t_i,t_{i+1})$ be the flow map satisfying the following ODE:
\begin{equation*}
\begin{cases}
    \frac{\partial \phi}{\partial t}(x;t_i, t) = f_r( \phi(x;t_i,t);B,C,D) \\
    \phi(x;t_i,t_i) = x
\end{cases}    
\end{equation*}
Moreover, let $r(x,y) =  \|y - \phi(x;t_i,t_{i+1})$, $L(x,y) = \frac{1}{2}\|r(x,y) \|_2^2$, then we have:
\begin{align*}
\frac{\partial L}{\partial y} &= r(x,y) \\
\frac{\partial L}{\partial x} &= \nabla_x \phi(x;t_i,t_{i+1}) r(x,y)
\end{align*}

Using the adjoint equation method, and recall that $\nabla f = G$, the derivative $\frac{\partial L}{\partial x}$ is equal to $\tilde r(t_{i+1})$, where $\tilde r(\cdot)$ solves:
\begin{equation*}
\begin{cases}
\frac{\partial \tilde r}{\partial t}(t) = G^* \tilde r \\
\tilde r(t_i) = r(x,y)
\end{cases}
\end{equation*}



# Generating test examples

In this part we generate test examples for our model. We first consider the following 2D linear acoustic equation:
\begin{equation*}
\begin{cases}
p_t + K(u_x + v_y) = 0 & (x,y) \in \Omega = [0,3]\times [0,2] \\
u_t + \rho^{-1}p_x = 0 \\
v_t + \rho^{-1}p_y = 0 \\
u(t = 0) = v(t = 0) = p(t = 0) = 0
\end{cases}
\end{equation*}

The boundary condition is given by following:

- Left boundary($x = 0$): We use an inflow boundary condition here. The boundary condition is parametrized by a parameter $\theta$. 
\begin{align*}
    p(0,y,t) &= (\theta t + 1) \sin((1 + \theta^2 y^2)t) \\
    u(0,y,t) &= \frac{K}{c} u(0,y,t), \text{ where } c^2 = \frac{K}{\rho} \\
    v(0,y,t) &= 0.5
\end{align*}
- Right boundary($x = 1$): Extrap(outflow) boundary.
- Bottom boundary($y = 0$): Reflection boundary.
- Upper boundary($y = 1$): Reflection boundary.

In [1]:
from clawpack import riemann
import numpy as np
import os
from clawpack.pyclaw.util import run_app_from_main
from clawpack.pyclaw import plot
import re
from math import floor

In [2]:
os.getcwd()

'/oden/yuhang/Operator Inference'

In [90]:
# This readdata function allow us to read the solution of clawpack

localpath = os.getcwd()

def readdata(Nt):
    nummod1 = re.compile(r'-[0-9]\.[0-9]+e[+-][0-9]+|[0-9]\.[0-9]+e[+-][0-9]+')
    nummod2 = re.compile(r'\d+')
    parammod = re.compile(r'[a-zA-Z_]{2,20}')

    for tind in range(Nt+1):
        filename = './_output/fort.q' + str(tind).rjust(4,'0')
        with open(filename,'r') as file:
            wholeline = file.readlines()
            paramnum = wholeline.index('\n')

            if tind == 0:
                for ind in range(paramnum):
                    cline = wholeline[ind]
                    cline = cline.replace(' ','')
                    cline = cline.replace('\n','')
                    paramname = parammod.findall(cline)[0]
                    num1 = nummod1.findall(cline)
                    num2 = nummod2.findall(cline)
                    if len(num1) == 0:
                        val = float(num2[0])
                    else:
                        val = float(num1[0])
                    print('The parameter %s is set as ' % paramname, val)

                    if paramname == 'mx':
                        mx = val
                    elif paramname == 'my':
                        my = val

                N = int(mx * my)
                mx = int(mx)
                my = int(my)

                q = np.zeros([mx,my,Nt+1])
                v = np.zeros([mx,my,Nt+1])
                u = np.zeros([mx,my,Nt+1])
            currentind = 0
            #print(paramnum + 1, len(wholeline))
            for ind in range(paramnum + 1, len(wholeline)):
                currentx = currentind % mx
                currenty = floor(currentind / mx)
            #    print(currentind,tind,currentx,currenty)
                cline = wholeline[ind]
                if cline.find('nan') == 0:
                    #print('We find nan at file number', tind)
                    raise Exception('We find nan')
                cline = cline.strip()
                if cline == '':
                    continue
                #print(tind,currentx,currenty,cline)
                data = nummod1.findall(cline)
                q[currentx,currenty,tind] = float(data[0])
                v[currentx,currenty,tind] = float(data[1])
                u[currentx,currenty,tind] = float(data[2])
                currentind = currentind + 1
    return q,v,u

NameError: name 'os' is not defined

In [66]:


from clawpack import riemann
import numpy as np
import os

Nt = 100; Tfinal = 10;
xl = 0;       xr = 3; 
yl = 0;       yr = 2;
mx = 60;      my = 40;
rho = 1.0;    bulk = 4.0;

def setup(kernel_language='Fortran', use_petsc=False, outdir='./_output', 
              solver_type='classic', time_integrator='SSP104', ptwise=False,
              disable_output=False):
    """
    Example python script for solving the 2d acoustics equations.
    """
    if use_petsc:
        from clawpack import petclaw as pyclaw
    else:
        from clawpack import pyclaw

    if solver_type == 'classic':
        if ptwise:
            solver = pyclaw.ClawSolver2D(riemann.acoustics_2D_ptwise)
        else:
            solver = pyclaw.ClawSolver2D(riemann.acoustics_2D)
        solver.dimensional_split=True
        solver.cfl_max = 0.5
        solver.cfl_desired = 0.45
        solver.limiters = pyclaw.limiters.tvd.MC
    elif solver_type=='sharpclaw':
        solver=pyclaw.SharpClawSolver2D(riemann.acoustics_2D)
        solver.time_integrator=time_integrator
        if solver.time_integrator=='SSP104':
            solver.cfl_max = 0.5
            solver.cfl_desired = 0.45
        elif solver.time_integrator=='SSPLMMk2':
            solver.lmm_steps = 3
            solver.lim_type = 2
            solver.cfl_max = 0.25
            solver.cfl_desired = 0.24
        else:
            raise Exception('CFL desired and CFL max have not been provided for the particular time integrator.')
    
    solver.bc_lower[0]=pyclaw.BC.custom
    solver.user_bc_lower = wave_maker_bc
    solver.bc_upper[0]=pyclaw.BC.extrap
    solver.bc_lower[1]=pyclaw.BC.wall
    solver.bc_upper[1]=pyclaw.BC.wall

    x = pyclaw.Dimension(xl,xr,mx,name='x')
    y = pyclaw.Dimension(yl,yr,my,name='y')
    domain = pyclaw.Domain([x,y])

    num_eqn = 3
    state = pyclaw.State(domain,num_eqn)

    rho  = 1.0  # Material density
    bulk = 4.0  # Material bulk modulus
    cc = np.sqrt(bulk/rho)  # sound speed
    zz = rho*cc             # impedance
    state.problem_data['rho']= rho
    state.problem_data['bulk']=bulk
    state.problem_data['zz']= zz
    state.problem_data['cc']= cc
    state.problem_data['theta'] = theta  # parameter of boundary condition

    solver.dt_initial=np.min(domain.grid.delta)/state.problem_data['cc']*solver.cfl_desired

    qinit(state)

    claw = pyclaw.Controller()
    claw.keep_copy = True
    if disable_output:
        claw.output_format = None
    claw.solution = pyclaw.Solution(state,domain)
    claw.solver = solver
    claw.outdir = outdir
    claw.num_output_times = Nt
    claw.tfinal = Tfinal
    claw.setplot = setplot

    return claw

In [67]:
def qinit(state,width=0.2):
    X, Y = state.grid.p_centers
    r = np.sqrt(X**2 + Y**2)

    state.q[0,:,:] = 0
    state.q[1,:,:] = 0.
    state.q[2,:,:] = 0.

In [68]:
def walldata(x,y,t,theta = 1):
    p = np.sin( (1 + theta *  y ** 2) * t)
    return p

def qbcdata(t,theta = 1):
    ylist = np.linspace(yl,yr,my+1)
    ylist = np.reshape(ylist,[my+1,1])
    pbc = walldata(0,ylist,t,theta)
    ubc = walldata(0,ylist,t,theta) / bulk * rho
    vbc = 0.5 * np.ones([my+1,1])
    pbc = np.concatenate([pbc,ubc,vbc])
    return pbc


def wave_maker_bc(state,dim,t,qbc,auxbc,num_ghost):
    "Generate waves at left boundary as if there were a moving wall there."
#     if dim.on_lower_boundary:
#      #   print(num_ghost,qbc[:,:,:].shape,type(qbc),num_ghost)
#         qbc[0,:num_ghost,:]=qbc[0,num_ghost,:]
#         t=state.t
# #        my = (qbc[0,num_ghost,:].shape)[0] -2 * num_ghost
#      #   print(my)

    t = state.t
    hx = (xr - xl) / mx
    rho = state.problem_data['rho']
    bulk = state.problem_data['bulk']
    c = np.sqrt(rho * bulk)
    theta = state.problem_data['theta']
    v = c

    hy = (yr - yl) / my
    yspace = np.linspace(yl - 3 * hy / 2,yr + 3 *  hy / 2,my + 4)

    for ibc in range(num_ghost):
        xc = -(num_ghost - ibc - 0.5) * hx
        t2 = t + abs(xc) / v
        qbc[0,ibc,:] = walldata(0,yspace,t2,theta)
        qbc[1,ibc,:] = walldata(0,yspace,t2,theta) / bulk * rho
        qbc[2,ibc,:] = 0.5

In [ ]:
s = qbcdata(1,0.2)
s
len(s)

In [ ]:
pbc

In [26]:
def setplot(plotdata):
    """ 
    Plot output with VisClaw.
    This example demonstrates how to plot a 1D projection from 2D data.
    """ 

    from clawpack.visclaw import colormaps

    plotdata.clearfigures()  # clear any old figures,axes,items data
    
    # Figure for pressure
    plotfigure = plotdata.new_plotfigure(name='Pressure', figno=0)

    # Set up for axes in this figure:
    plotaxes = plotfigure.new_plotaxes()
    plotaxes.title = 'Pressure'
    plotaxes.scaled = True      # so aspect ratio is 1

    # Set up for item on these axes:
    plotitem = plotaxes.new_plotitem(plot_type='2d_pcolor')
    plotitem.plot_var = 0
    plotitem.pcolor_cmap = colormaps.yellow_red_blue
    plotitem.add_colorbar = True

    # Figure for scatter plot
    plotfigure = plotdata.new_plotfigure(name='scatter', figno=1)

    # Set up for axes in this figure:
    plotaxes = plotfigure.new_plotaxes()
    plotaxes.title = 'Scatter plot'

    # Set up for item on these axes: scatter of 2d data
    plotitem = plotaxes.new_plotitem(plot_type='1d_from_2d_data')
    
    def p_vs_r(current_data):
        # Return radius of each patch cell and p value in the cell
        from pylab import sqrt
        x = current_data.x
        y = current_data.y
        r = sqrt(x**2 + y**2)
        q = current_data.q
        p = q[0,:,:]
        return r,p

    plotitem.map_2d_to_1d = p_vs_r
    plotitem.plot_var = 0
    plotitem.plotstyle = 'ob'
    
    return plotdata

In [27]:
path = os.getcwd()

In [15]:
if __name__ == "__main__":
    from clawpack.pyclaw.util import run_app_from_main
    from clawpack.pyclaw import plot
    
    #thetalist = [0.2,0.3,0.4,0.5]
    thetalist = [0.2]
    Ntheta = len(thetalist)
    qlist = np.zeros([mx,my,Nt+1,Ntheta])
    vlist = np.zeros([mx,my,Nt+1,Ntheta])
    ulist = np.zeros([mx,my,Nt+1,Ntheta])
    for ind in range(Ntheta):
        theta = thetalist[ind]
        output = run_app_from_main(setup, setplot)
        [q,u,v] = readdata(Nt)
        qlist[:,:,:,ind] = q
        ulist[:,:,:,ind] = u
        vlist[:,:,:,ind] = v
    output = run_app_from_main(setup, setplot)
    #plot.html_plot('./_output', 'ascii', setplot)
    

NameError: name 'mx' is not defined

In [78]:
qlist.shape

(60, 40, 101, 1)

In [37]:
# Reshape qlist into a matrix
qtraj = np.reshape(qlist,[mx * my, Nt + 1, Ntheta])
utraj = np.reshape(ulist,[mx * my, Nt + 1, Ntheta])


The first test we need to do is trying to recover the result from classic operator inference.

In this example, we fixed the quantity of interest $q$ as the overall data $p(:,:,t)$, and $A$ be the matrix we get from doing svd. We first let $C = 0$ so that there is no quadratic terms in the system. i.e. We are doing the following optimization problem:
\begin{equation*}
    \min_{B \in R^{r \times r}, D \in R^{r \times m}} \sum_{i,j = 1}^{Nx,Ny} \sum_{k = 1}^{N_t} \|A \hat x - p(x_i,y_j,t_k) \|_2^2 \text{ s.t. } \hat x(t) = B \hat x + C \hat x \otimes \hat x + D(p^T,u^T,v^T)^T_{\text{boundary}}, \hat x (0) = 0  
\end{equation*}

We will try many paramter here.


Recall $\mathcal{G}:R^r \to R^r,B \in R^{r \times r}, C \in R^{r \times s}$, and 

\begin{align*}
\mathcal{G}u &= Bu + C(x \otimes u + u\otimes x) =Bu + C\circ I (xu^T + ux^T) \\
\mathcal{G}^*v &= B^* v + [I^*(C^* v) + (I^*(C^* v))^T ]x
\end{align*}






In [122]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 1,include_bias = False)

In [ ]:
# Computing obstimelst

obstimelst = np.linspace(0,T,Nt + 1)


In [129]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [121]:
def G(u,x,B,C):
    s = int(r * (r + 1) / 2)
    indicelist = np.triu_indices(r)
    tmp = u * x.T + x * u.T
    tmp2 = tmp[indicelist]
    tmp2 = tmp2.reshape([s,1])
    answ = np.dot(B,u) + np.dot(C,tmp2)
    answ = answ.reshape(r,1)
    return answ

def G_adj(v,x,B,C):
    indicelist = np.triu_indices(r)
    CTv = np.dot(C.T,v)
    A = np.zeros([r,r])
    A[indicelist] = np.array(list(CTv.T))
    answ = np.dot(A + A.T, x) + np.dot(B.T,v)
    answ = answ.reshape(r,1)
    return answ

# Testing on the adjoint operator

# B = np.random.rand(r,r)
# #B = np.zeros([r,r])
# C = np.random.rand(r,s)
# for i in range(10):
#     u = np.random.rand(r,1)
#     v = np.random.rand(r,1)
#     x = np.random.rand(r,1)
#     gu = G(u,x,B,C)
#     gtv = G_adj(v,x,B,C)
#     S1 = np.dot(gu.T,v); S2 = np.dot(u.T,gtv)
#     print(S1,S2)

In [165]:
class goam:
    # Class GOAM is used to manage all the problem using the operator inference on general manifold
    # To create a goam object, please feed it with the following parameter:
    #   1. rdim: the dimension of the reduced variable,   default: 15
    #   2. xlst: high fidelity solution list           default: None
    #   3. Tstart: The start of the computation        default: 0
    #   4. QoIlst: quantity of interest list:          default: None
    #   5. inputlst: input on boundary                 default: None
    #   6. obstimelst: time for observation happens    default: np.linspace(0,1,11) 
    #   7. cpttimelst: time for 
    #
    #       Note: cpttimelst and cpttimelst will always include 0 as their starter
    #             obstimelst doesnt need to do that
    #
    #   7. solver: solver for the underlying ODE       default: RK4
    
    def __init__(self, r = 15, xlst = None,  Tstart = 0, QoIlst = None, inputlst = None, obstimelst = np.linspace(0,1,11), cpttimelst = None, rdim = 15, solver = 'RK4'):
        self.xlst = xlst
        self.QoIlst = QoIlst
        self.obstimelst = obstimelst
        self.inputlst = inputlst
        self.r = rdim
        self.Tstart = Tstart
        
        m = self.inputlst.shape[0]
        d = self.QoIlst.shape[0]
        r = rdim
        s = int(rdim * (rdim + 1) / 2)
        self.A = np.zeros([m,r])
        self.B = np.zeros([r,r])
        self.C = np.zeros([r,s])
        self.D = np.zeros([r,d])
        
        self.Nt_obs = len(obstimelst)
        self.Nt_cpt = len(obstimelst)
        if cpttimelst is None:
            self.cpttimelst = obstimelst
        else:
            self.cpttimelst = cpttimelst
                
        self.Tfinal = obstimelst[-1]
        self.Tstart = Tstart
        
        self.xrlst_cpt = np.zeros([r,self.Nt_cpt])
        self.xrlst_obs = np.zeros([r,self.Nt_obs])
        self.adjlst_cpt = np.zeros([r,self.Nt_cpt])
        self.adjlst_obs = np.zeros([r,self.Nt_obs])
        
        self.solver = 'RK4'
    
    def set_cpttimelst(self,cpttimelst):
        self.cpttimelst = cpttimelst
        self.Nt_cpt = len(cpttimelst)
        
    def forward(self):
        xr = np.zeros([r,1]);    
        Tfinal = self.Tfinal
        cpttimelst = self.cpttimelst
        obstimelst = self.obstimelst
        Nt_cpt = len(cpttimelst)    
        Nt_obs = len(obstimelst)
        indicelist = np.triu_indices(r)
        ind_obs = 0
        
        xrlst = np.zeros([r,])
        
        t = Tstart
        if t == obstimelst[0]:
            xrlst[:,ind_obs] = xr
            ind_obs = ind_obs + 1
        
        for ind_cpt in range(Nt_cpt - 1):
            # using RK4 for evolving the system step
            oldt = cpttimelst[ind_cpt]
            newt = cpttimelst[ind_cpt + 1]
            dt = newt - oldt
            
            t1 = oldt
            xrt1 = xr
            qbc = qbcdata(t1,theta)    
            tmp = xrt1 * xrt1.T;        tmp = tmp[indicelist]
            K1 = B * xrt1 + C * tmp + D * qbc

            t2 = oldt + 1/2 * dt
            xrt2 = xr + dt / 2 * K1
            qbc = qbcdata(t2,theta)
            tmp = xrt2 * xrt2.T;        tmp = tmp[indicelist]
            K2 = B * xrt2 + C * tmp + D * qbc

            t3 = oldt + 1/2 * dt
            qbc = qbcdata(t3,theta)
            xrt3 = xr + dt/2 * K2
            tmp = xrt3 * xrt3.T;        tmp = tmp[indicelist]
            K3 = B * xrt3 + C * tmp + D * qbc

            t4 = oldt + dt
            qbc = qbcdata(t4, theta)
            xrt4 = xr + dt * K3
            tmp = xrt4 * xrt4.T;        tmp = tmp[indicelist]
            K4 = B * xrt4 + C * tmp + D * qbc 

            xr = xr + 1/6 * dt * (K1 + 2 * K2 + 2 * K3 + K4)
            
            xrlst_
            
            t = Nt_cpt(ind_cpt + 1)
            if t + 1e-7 >= obstimelst[ind_obs]:
                xrlst_[:,ind_obs] = xr
                ind_obs = ind_obs + 1             
            
            self.

        return 

        
    
    
        

SyntaxError: invalid syntax (1078786353.py, line 71)

In [167]:
a = None
a is None

True

In [151]:
66len(np.linspace(0,1,11))

11

In [132]:
s = GOAM()

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'x']

In [128]:
r = 15   # The dimension of the reduced variable
#xr = np.zeros([r,1])  # The initial value of the reduced variable
A = np.zeros([r,1])
B = np.zeros([r,r])
C = np.zeros([r,s])
D = np.zeros([r,m])
dt = T / Nt / 3

# obstimelst is the moment when we make the observation, while cpttimelst is the moment we use to do computation
cpttimelst = np.linspace(0,T,3 * Nt + 1)  
obstimelst = np.linspace(0,T,Nt + 1)      





def eq_reduced(r,A,B,C,D,theta,obstimelst,cpttimelst):
    # This function helps to evolve the reduced variable in latent space,specifically
    # dx / dt = Bx + C x\otimes x + Dp
    # We take parameter B,C,D for the operator, and use RK4 for solving the equation
    # obstimelst is the list of when to make observation
    # This function helps to evolve the re
    
    xr = np.zeros([r,1]);    T = obstimelst[-1]
    Nt_cpt = len(cpttimelst);    Nt_obs = len(obstimelst)
    xrlist = np.zeros([r,Nt_obs])
    indicelist = np.triu_indices(r)
    
    ind_obs = 0
    for ind_cpt in range(Nt):
        t1 = ind * dt
        xrt1 = xr
        # using RK4 for evolving the system step
        qbc = qbcdata(t1,theta)    
        tmp = xrt1 * xrt1.T;        tmp = tmp[indicelist]
        K1 = B * xrt1 + C * tmp + D * qbc
        
        t2 = (ind + 1 / 2) * dt
        xrt2 = xr + t / 2 * K1
        qbc = qbcdata(t2,theta)
        tmp = xrt2 * xrt2.T;        tmp = tmp[indicelist]
        K2 = B * xrt2 + C * tmp + D * qbc
        
        t3 = (ind + 1 / 2) * dt
        qbc = qbcdata(t3,theta)
        xrt3 = xr + t/2 * K2
        tmp = xrt3 * xrt3.T;        tmp = tmp[indicelist]
        K3 = B * xrt3 + C * tmp + D * qbc
        
        t4 = (ind + 1) * dt
        qbc = qbcdata(t4, theta)
        xrt4 = xr + t * K3
        tmp = xrt4 * xrt4.T;        tmp = tmp[indicelist]
        K4 = B * xrt4 + C * tmp + D * qbc 
        
        xr = xr + 1/6 * dt * (K1 + 2 * K2 + 2 * K3 + K4)
        xrlist[:,ind + 1] = xr
    
    return 

NameError: name 'm' is not defined

In [125]:
s = [1,2,3,4,5,777]
len(s)
s[len(s) - 1]

777

In [ ]:
def adj_reduced(reslist,xrlist,T,Nt,A,B,C,D,theta):
    # This function aims to evolve the adjoint equation in the latent space
    #  dr / dt (t) = G^*(t,x,B,C)
    # Recall from the previous result, G^* v = B^*v + (I*(C*v) + [I^*(C^*v)]^T)x
    r = 0
    rlist_adj = zeros(r,Nt+1)
    dt = T / Nt
    
    x = xrlist[:,Nt]
    rlist_adj[:,0] = np.dot(A.T)
    
    for ind in range(Nt):
    
        x = xrlist[:,Nt - ind]
        x_next = xrlist[:,Nt - ind - 1]
        
        t1 = ind * dt
        xt1 = x
        rt1 = r
        K1 = G_adj(rt1,xt1,B,C)
        
        t2 = (ind + 1/2) * dt
        xt2 = 1/2 * (x + x_next)
        rt2 = r + 1/2 * dt * K1
        K2 = G_adj(rt2,xt2,B,C)
        
        t3 = (ind + 1/2) * dt
        xt3 = 1/2 * (x + x_next)
        rt3 = r + 1/2 * dt * K2
        K3 = G_adj(rt3,xt3,B,C)
        
        t4 = ind * dt
        xt4 = x_next
        rt4 = r + dt * K3
        K4 = G_adj(rt4,xt4,B,C)
        
        r = r + 1/6 * dt * (K1 + 2 * K2 + 2 * K3 + K4)
        reslist[:,ind + 1] = r

    return rlist_adj

In [ ]:
res = np.dot(A,x)
reslist = 

In [ ]:
def gradient_B(xrlist,A,B,D):
    # We compute the derivative of the loss function regarding the operator B
    
    
    
    
    
    
    

In [96]:
indicelist = np.triu_indices(r)
indicelist

(array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,
         7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,
         9,  9,  9, 10, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 13, 13,
        14]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  1,  2,
         3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  2,  3,  4,  5,  6,
         7,  8,  9, 10, 11, 12, 13, 14,  3,  4,  5,  6,  7,  8,  9, 10, 11,
        12, 13, 14,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  5,  6,  7,
         8,  9, 10, 11, 12, 13, 14,  6,  7,  8,  9, 10, 11, 12, 13, 14,  7,
         8,  9, 10, 11, 12, 13, 14,  8,  9, 10, 11, 12, 13, 14,  9, 10, 11

In [90]:
s = np.arange(4)
s = np.reshape(s,[4,1])
ind = np.triu_indices(4)
ind

(array([0, 0, 0, 0, 1, 1, 1, 2, 2, 3]), array([0, 1, 2, 3, 1, 2, 3, 2, 3, 3]))

In [94]:
S = s * s.T
tmp = S[ind]
tmp

array([0, 0, 0, 0, 1, 2, 3, 4, 6, 9])

In [9]:
import numpy as np
indicelist = np.triu_indices(3)
s = np.arange(9).reshape([3,3])
t = s[indicelist]

In [8]:
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
t

array([0, 1, 2, 4, 5, 8])

In [12]:
z = np.zeros([3,3])

In [13]:
z[indicelist] = t

In [14]:
z

array([[0., 1., 2.],
       [0., 4., 5.],
       [0., 0., 8.]])

In [145]:
def s(x = np.random.rand(2)):
    return 2 * x

In [146]:
s()

array([1.71827847, 0.52755883])

In [136]:
s

<function __main__.s(x=array([0.82248929, 0.9650524 ]))>

In [137]:
s()

array([1.64497857, 1.9301048 ])

In [138]:
s()

array([1.64497857, 1.9301048 ])

In [139]:
s()

array([1.64497857, 1.9301048 ])

In [140]:
s()

array([1.64497857, 1.9301048 ])

In [159]:
class s():
    def __init__(self):
        self.t = 2

In [163]:
class s():
    def add(self):
        self.t = self.t + 1

In [164]:
tt = s()
tt.add
tt.t

AttributeError: 's' object has no attribute 't'

In [170]:
a = 3
if a == 5:
    print(5)
else:
    

In [175]:
import numpy as np
A = np.arange(9).reshape(3,3)
b = np.arange(3).reshape(3,1)
A.dot(b)

array([[ 5],
       [14],
       [23]])

In [173]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [174]:
b

array([[0],
       [1],
       [2]])

In [2]:
from goam_class.ipynb import GOAM

ModuleNotFoundError: No module named 'goam_class'